apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: prestashop/prestashop:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_USER
            - name: DB_PASSWD
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_PASS
            - name: PS_INSTALL_AUTO
              value: "1"
            - name: PS_DEV_MODE
              value: "1"

