apiVersion: apps/v1
kind: Deployment
metadata:
  name: prestashop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prestashop
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
        - name: prestashop
          image: prestashop/prestashop:latest
          ports:
            - containerPort: 4000
          env:
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_HOST
            - name: PRESTASHOP_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_NAME
            - name: PRESTASHOP_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_USER
            - name: PRESTASHOP_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prestashop-mariadb-secret
                  key: DB_PASS
          volumeMounts:
            - name: prestashop-data
              mountPath: /var/www/html
      volumes:
        - name: prestashop-data
          emptyDir: {}

