apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wordpress-ingress
  namespace: default
  annotations:
    # Traefik: auf HTTPS-EntryPoint binden
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # (optional, für ältere Controller) zusätzlich die Klassik-Annotation:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: wpf.drachenbyte.ddns-ip.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wordpress-service
                port:
                  number: 80              
  tls:
    - hosts:
        - wpf.drachenbyte.ddns-ip.net
      secretName: wpf-secret              

