name: MariaDB Backup to S3

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    env:
      DB_ENDPOINT: ${{ secrets.DB_HOST }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USERNAME }}
      DB_PASS: ${{ secrets.DB_PASSWORD }}
      S3_BUCKET: wp-presta-backups
      AWS_REGION: eu-west-3
      EC2_IP: ${{ secrets.EC2_PUBLIC_IP }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Dump MariaDB and upload to S3 via EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@$EC2_IP <<EOF
            set -e

            TIMESTAMP=\$(date +%F-%H%M)
            BACKUP_FILE="/home/ubuntu/mariadb-backup-\$TIMESTAMP.sql"

            echo "Dumping database..."
            mysqldump -h $DB_HOST -u $DB_USER -p"$DB_PASS" $DB_NAME > \$BACKUP_FILE

            echo "Uploading to S3..."
            aws s3 cp \$BACKUP_FILE s3://$S3_BUCKET/db-backups/\$(basename \$BACKUP_FILE) --region $AWS_REGION

            echo "Backup complete: \$BACKUP_FILE"
          EOF

